---
name: Checks

on: [push] # trigger

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # runner,
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # allow to use another pre-made action that's provided in github actions respository
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"